#!/usr/bin/env bash
# A script that loops through 1 to 10 using while

s=1

while [ $s -le 10 ]
do
    if [ $s -eq 4 ]
    then
        echo "bad luck"
    elif [ $s -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((s++))
done